### ISSUE TITLE
Database: Three tables to be generated, users, transactions and companies (provided by the client)

### ISSUE THREAD

**Issue by samtweedie** [Jackson-Stewart/Industrial-Team-Project---Eco-Friendly-Banking-App#7]

**Comment by kayeeliu3** [comment]
# Minimum Fields (Subject to change !)

### USERS TABLE
- name
- accountNumber
- amountOfMoney
- currentGreenScore
- currentStreak

### COMPANY TABLE
- name
- accountNumber
- spendingCategory
- carbonEmissionRating
- wasteManagementRating
- sustainabilityPracticesRating
- amountOfMoney
- summary

* Be aware of floating point errors.

### TRANSACTIONS 
- moneyTransferred
- accountFrom
- accountTo
- calculatedGreenScore
- timestamp

**Comment by kayeeliu3** [comment]
AmazonDB seems to be the way to go. NoSQL, scalable, in-built security and maintainability systems, good integration with Amazon API Gateway and Lambda.
